### ISSUE TITLE
Not available on packagist.

### ISSUE THREAD

**Issue by Hexmage** [smartexcan/magento2-page-builder-require-js-fix#1]
Hallo smarexcan,

I would like to use your code. But to make it more stable (and not be surprised by sudden changes). I would like it to be a package on packagist. Could you set this up?

**Comment by smartexcan** [comment]
Hey, I've uploaded the package on packagist now!
https://packagist.org/packages/smartex/module-page-builder-require-js-fix

Sorry for the delay
